version: "3.8"

services:

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: appdb
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - backend

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./data/mongo:/data/db
    ports:
      - "27017:27017"
    networks:
      - backend

  redis:
    image: redis:8.0
    container_name: redis
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./data/redis:/data
    ports:
      - "6379:6379"
    networks:
      - backend

  kafka:
    image: apache/kafka:latest
    container_name: kafka
    hostname: kafka
    restart: always

    ports:
      - "9094:9094"   # external
      - "9092:9092"   # internal (optional expose)

    environment:
      # KRaft mode
      KAFKA_NODE_ID: 0
      KAFKA_PROCESS_ROLES: controller,broker
      KAFKA_CONTROLLER_QUORUM_VOTERS: 0@kafka:9093

      # Listeners
      KAFKA_LISTENERS: >
        PLAINTEXT://0.0.0.0:9092,
        CONTROLLER://0.0.0.0:9093,
        EXTERNAL://0.0.0.0:9094

      # Advertised (QUAN TRỌNG NHẤT)
      KAFKA_ADVERTISED_LISTENERS: >
        PLAINTEXT://kafka:9092,
        EXTERNAL://localhost:9094

      # Map protocol
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: >
        PLAINTEXT:PLAINTEXT,
        EXTERNAL:PLAINTEXT,
        CONTROLLER:PLAINTEXT

      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      KAFKA_HEAP_OPTS: "-Xmx512m -Xms512m"
    volumes:
      - ./data/kafka:/kafka/data
    networks:
      - backend

networks:
  backend:
    external: true
