server:
  port: 8086
  servlet:
    context-path: /wallet

spring:
  application:
    name: wallet-service
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/wallet_service}
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_PASSWORD:root}
    driver-class-name: "com.mysql.cj.jdbc.Driver"
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

app:
  services:
    otp: http://localhost:8081/otp
    identity: http://localhost:8080/identity
