server:
  port: 8081
  servlet:
    context-path: /otp
spring:
  application:
    name: otp-service
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://root:root@mongodb:27017/otp_service?authSource=admin}
      auto-index-creation: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:kafka:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
